name: user_interview_bithealth_muhammad_randi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  d_info: ^0.0.8
  d_method: 0.0.2
  d_view: 0.0.3
  d_input: ^0.0.2
  photo_view: 0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
